const groceryData = [
  { id: 1, title: "Apples", price: 120, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/1/15/Red_Apple.jpg" },
  { id: 2, title: "Bananas", price: 60, unit: "1 dozen", img: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Banana-Single.jpg" },
  { id: 3, title: "Oranges", price: 80, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Orange-Fruit-Pieces.jpg" },
  { id: 4, title: "Mangoes", price: 150, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/9/90/Hapus_Mango.jpg" },
  { id: 5, title: "Grapes", price: 90, unit: "500g", img: "https://upload.wikimedia.org/wikipedia/commons/1/18/Table_grapes_on_white.jpg" },
  { id: 6, title: "Pineapple", price: 70, unit: "each", img: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Pineapple_and_cross_section.jpg" },
  { id: 7, title: "Watermelon", price: 40, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Watermelon_cross_BNC.jpg" },
  { id: 8, title: "Tomatoes", price: 30, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/8/89/Tomato_je.jpg" },
  { id: 9, title: "Potatoes", price: 25, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/6/60/Fresh_potatoes.jpg" },
  { id: 10, title: "Onions", price: 35, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/7/73/Onion_on_White.JPG" },
  { id: 11, title: "Carrots", price: 40, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Carrots.jpg" },
  { id: 12, title: "Cabbage", price: 30, unit: "each", img: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Cabbage_and_cross_section_on_white.jpg" },
  { id: 13, title: "Cauliflower", price: 45, unit: "each", img: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Cauliflower.JPG" },
  { id: 14, title: "Spinach", price: 25, unit: "bunch", img: "https://upload.wikimedia.org/wikipedia/commons/0/05/Spinach_leaves.jpg" },
  { id: 15, title: "Green Peas", price: 60, unit: "500g", img: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Green_peas_in_pods_-_Studio.jpg" },
  { id: 16, title: "Rice", price: 55, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Rice_white_raw.jpg" },
  { id: 17, title: "Wheat Flour", price: 45, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/5/56/Atta_flour.jpg" },
  { id: 18, title: "Sugar", price: 42, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/3/36/Sugar_white_crystals.jpg" },
  { id: 19, title: "Salt", price: 20, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/2/29/Salt_shaker_on_white_background.jpg" },
  { id: 20, title: "Milk", price: 55, unit: "1L", img: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Milk_glass.jpg" },
  { id: 21, title: "Butter", price: 480, unit: "500g", img: "https://upload.wikimedia.org/wikipedia/commons/6/69/Butter.jpg" },
  { id: 22, title: "Cheese", price: 550, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Cheese.jpg" },
  { id: 23, title: "Bread", price: 40, unit: "each", img: "https://upload.wikimedia.org/wikipedia/commons/5/5a/White_bread.jpg" },
  { id: 24, title: "Eggs", price: 60, unit: "dozen", img: "https://upload.wikimedia.org/wikipedia/commons/2/22/Eggs_in_carton.jpg" },
  { id: 25, title: "Chicken", price: 220, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/1/11/Raw_chicken_quarters.jpg" },
  { id: 26, title: "Fish", price: 300, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/4/41/Raw_salmon_fillet.jpg" },
  { id: 27, title: "Lentils (Dal)", price: 90, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Red_lentils.jpg" },
  { id: 28, title: "Chickpeas", price: 80, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Chickpeas-Bengal_gram.jpg" },
  { id: 29, title: "Cooking Oil", price: 160, unit: "1L", img: "https://upload.wikimedia.org/wikipedia/commons/8/85/Soybean_oil_in_glass_bottle.jpg" },
  { id: 30, title: "Tea", price: 450, unit: "1kg", img: "https://upload.wikimedia.org/wikipedia/commons/3/39/Loose_leaf_black_tea.jpg" },
];

module.exports = { data: groceryData};
